- name: Patch a service
  hosts: all
  become: true
  tasks:
    - name: Echo package
      debug:
        msg: "{{ package }}"
    - name: Upgrade package
      package:
        name: "{{ package }}"
        state: latest
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
